platform :ios, '13.0'

source 'https://gitlab.linphone.org/BC/public/podspec.git'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'

  pod 'linphone-sdk-novideo', '~> 5.2.95'
  #pod 'linphone-sdk/basic-frameworks', '~> 5.2.45'
  #pod 'linphone-sdk/app-extension-swift', '~> 5.2.45'
end

target 'Plugin' do
  capacitor_pods
end

target 'PluginTests' do
  capacitor_pods
end


